# Site settings
title: Jerry Blog
SEOTitle: 杰瑞的博客 | Jerry Blog
header-img: img/post-bg-desk.jpg
email: liangwenqi1126@gmail.com
description: "Every failure is leading towards success."
keyword: "BY, BY Blog, 杰瑞的博客, liangwenqi, iOS, Apple, iPhone"
url: "http://xiqe.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/xiqe/xiqe.github.io" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Ctrip | Lu | Glodon"
sidebar-avatar: /img/about-BY-gentle.png      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: true
weibo_username:     xiqe
#zhihu_username:     xiqe
github_username:    xiqe
facebook_username:  1821199290
#twitter_username:   xiqe




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: a51f17437366f7361dd9                            #生成的clientID
  clientSecret: a8d253a9190ff489412bdaa96c129eb4d3c336a4    #生成的clientSecret
  repo: xiqe.github.io    #仓库名称
  owner: xiqe    #github用户名
  admin: xiqe
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
ba_track_id: 2f914bc01190850d8740e53b747adc3b

# Google Analytics
ga_track_id: 'UA-132991899-1'            # Format: UA-xxxxxx-xx
ga_domain: holamundo.cn               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto



# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "前端外刊评论",
        href: "https://qianduan.group/"
    },{
        title: "大前端工程师-知乎",
        href: "https://zhuanlan.zhihu.com/bigfront"
    }
]
